# -*- coding: utf-8 -*-
"""expence tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10oO2DXGHh7l_AwE8etD_oHa4iGINdOkw
"""

import os
from datetime import datetime

FILE_NAME = "expenses.txt"


def add_expense():
    date = datetime.now().strftime("%Y-%m-%d")
    category = input("Enter expense category: ")
    try:
        amount = float(input("Enter expense amount: "))
        with open(FILE_NAME, "a") as file:
            file.write(f"{date},{category},{amount}\n")
        print("✅ Expense added successfully!")
    except ValueError:
        print("❌ Invalid amount!")


def view_expenses():
    if not os.path.exists(FILE_NAME):
        print("No expenses recorded yet.")
        return

    print("\n📋 All Expenses:")
    with open(FILE_NAME, "r") as file:
        for line in file:
            date, category, amount = line.strip().split(",")
            print(f"Date: {date} | Category: {category} | Amount: ₹{amount}")


def total_expense():
    total = 0
    if os.path.exists(FILE_NAME):
        with open(FILE_NAME, "r") as file:
            for line in file:
                _, _, amount = line.strip().split(",")
                total += float(amount)
    print(f"\n💰 Total Expense: ₹{total}")


def category_summary():
    summary = {}
    if os.path.exists(FILE_NAME):
        with open(FILE_NAME, "r") as file:
            for line in file:
                _, category, amount = line.strip().split(",")
                summary[category] = summary.get(category, 0) + float(amount)

    print("\n📊 Category-wise Summary:")
    for category, amount in summary.items():
        print(f"{category}: ₹{amount}")


def main():
    while True:
        print("\n💰 Expense Tracker")
        print("1. Add Expense")
        print("2. View Expenses")
        print("3. Total Expense")
        print("4. Category-wise Summary")
        print("5. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            add_expense()
        elif choice == "2":
            view_expenses()
        elif choice == "3":
            total_expense()
        elif choice == "4":
            category_summary()
        elif choice == "5":
            print("Thank you for using Expense Tracker!")
            break
        else:
            print("❌ Invalid choice!")


if __name__ == "__main__":
    main()